- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no

  tasks:
    - name: homebrew_tap
      homebrew_tap: tap={{item}}
      with_items:
        - homebrew/binary
        - homebrew/dupes
        - kawaz/itumono
    - name: homebrew update/upgrade
      homebrew: update_homebrew=yes upgrade_all=yes
    - name: homebrew install
      homebrew: >
        name={{ item.name }}
        state={{ item.state|default("latest") }}
        install_options={{ item.install_options|default() }}
      with_items:
        - name: binutils
        - name: coreutils
        - name: findutils
        - name: bash
        - name: bash-completion2
        - name: tmux
        - name: reattach-to-user-namespace
        - name: xz
        - name: unrar
        # devel
        - name: awscli
        - name: jq
        - name: git
        - name: mercurial
        - name: subversion
        - name: go
        - name: tig
        - name: lua
        # vim
        - name: vim
          install_options: with-lua,with-luajit
        - name: fontforge
          install_options: with-python
        # misc
        - name: docker
        - name: mysql
        - name: redis
        - name: packer
        - name: phantomjs
        - name: djbdns
        - name: imagemagick
        - name: ffmpeg
          install_options: with-faac,with-fdk-aac,with-ffplay,with-libvorbis,with-libvpx,with-openssl,with-opus,with-rtmpdump,with-x265
          state: latest
